In [ ]:
import pandas as pd 

data = {"employee name": [
    "Sudhi" ,"Aromal", "Danush", "Vivek", "Amal" ,"Gayatri"],

    "salary": [25000,25000,25000,30000,25000,30000],
    "Date of joining": ["03/06/2024", "24/08/2023" , "13/03/2025", "12/06/2021", "23/08/2025", "07/04/2021"],
    "Employee ID No": ["EMP125","EMP224","EMP785","EMP257","EMP025","EMP047"]
            }
f = pd.DataFrame(data)
f

  employee name  salary Date of joining Employee ID No
0         Sudhi   25000      03/06/2024         EMP125
1        Aromal   25000      24/08/2023         EMP224
2        Danush   25000      13/03/2025         EMP785
3         Vivek   30000      12/06/2021         EMP257
4          Amal   25000      23/08/2025         EMP025
5       Gayatri   30000      07/04/2021         EMP047

In [ ]:
working ='F:\AL ML project\AIML\company_sales_data.csv'
sales = pd.read_csv(working)
sales

,month_number,facecream,facewash,toothpaste,bathingsoap,shampoo,moisturizer,total_units,total_profit
0,1,2500,1500,5200,9200,1200,1500,21100,211000
1,2,2630,1200,5100,6100,2100,1200,18330,183300
2,3,2140,1340,4550,9550,3550,1340,22470,224700
3,4,3400,1130,5870,8870,1870,1130,22270,222700
4,5,3600,1740,4560,7760,1560,1740,20960,209600
5,6,2760,1555,4890,7490,1890,1555,20140,201400
6,7,2980,1120,4780,8980,1780,1120,29550,295500
7,8,3700,1400,5860,9960,2860,1400,36140,361400
8,9,3540,1780,6100,8100,2100,1780,23400,234000
9,10,1990,1890,8300,10300,2300,1890,26670,266700
10,11,2340,2100,7300,13300,2400,2100,41280,412800
11,12,2900,1760,7400,14400,1800,1760,30020,300200

In [10]:
print(sales.shape)
print(sales.describe())

(12, 9)
       month_number    facecream     facewash   toothpaste   bathingsoap  \
count     12.000000    12.000000    12.000000    12.000000     12.000000
mean       6.500000  2873.333333  1542.916667  5825.833333   9500.833333
std        3.605551   584.595172   316.733745  1242.032486   2348.095779
min        1.000000  1990.000000  1120.000000  4550.000000   6100.000000
25%        3.750000  2460.000000  1305.000000  4862.500000   8015.000000
50%        6.500000  2830.000000  1527.500000  5530.000000   9090.000000
75%        9.250000  3435.000000  1765.000000  6400.000000  10045.000000
max       12.000000  3700.000000  2100.000000  8300.000000  14400.000000

           shampoo  moisturizer  total_units   total_profit
count    12.000000    12.000000     12.00000      12.000000
mean   2117.500000  1542.916667  26027.50000  260275.000000
std     617.724931   316.733745   7014.36594   70143.659404
min    1200.000000  1120.000000  18330.00000  183300.000000
25%    1795.000000  1305.000000  21065.00000  210650.000000
50%    1995.000000  1527.500000  22935.00000  229350.000000
75%    2325.000000  1765.000000  29667.50000  296675.000000
max    3550.000000  2100.000000  41280.00000  412800.000000

In [9]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   month_number  12 non-null     int64
 1   facecream     12 non-null     int64
 2   facewash      12 non-null     int64
 3   toothpaste    12 non-null     int64
 4   bathingsoap   12 non-null     int64
 5   shampoo       12 non-null     int64
 6   moisturizer   12 non-null     int64
 7   total_units   12 non-null     int64
 8   total_profit  12 non-null     int64
dtypes: int64(9)
memory usage: 992.0 bytes

In [12]:
sales.head(10)

,month_number,facecream,facewash,toothpaste,bathingsoap,shampoo,moisturizer,total_units,total_profit
0,1,2500,1500,5200,9200,1200,1500,21100,211000
1,2,2630,1200,5100,6100,2100,1200,18330,183300
2,3,2140,1340,4550,9550,3550,1340,22470,224700
3,4,3400,1130,5870,8870,1870,1130,22270,222700
4,5,3600,1740,4560,7760,1560,1740,20960,209600
5,6,2760,1555,4890,7490,1890,1555,20140,201400
6,7,2980,1120,4780,8980,1780,1120,29550,295500
7,8,3700,1400,5860,9960,2860,1400,36140,361400
8,9,3540,1780,6100,8100,2100,1780,23400,234000
9,10,1990,1890,8300,10300,2300,1890,26670,266700

In [14]:
sales.tail(10)

,month_number,facecream,facewash,toothpaste,bathingsoap,shampoo,moisturizer,total_units,total_profit
2,3,2140,1340,4550,9550,3550,1340,22470,224700
3,4,3400,1130,5870,8870,1870,1130,22270,222700
4,5,3600,1740,4560,7760,1560,1740,20960,209600
5,6,2760,1555,4890,7490,1890,1555,20140,201400
6,7,2980,1120,4780,8980,1780,1120,29550,295500
7,8,3700,1400,5860,9960,2860,1400,36140,361400
8,9,3540,1780,6100,8100,2100,1780,23400,234000
9,10,1990,1890,8300,10300,2300,1890,26670,266700
10,11,2340,2100,7300,13300,2400,2100,41280,412800
11,12,2900,1760,7400,14400,1800,1760,30020,300200

In [18]:
list(sales.columns)

['month_number',
 'facecream',
 'facewash',
 'toothpaste',
 'bathingsoap',
 'shampoo',
 'moisturizer',
 'total_units',
 'total_profit']